<a href="https://colab.research.google.com/github/agatagruza/private-ai/blob/master/SPAIC_Project2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project 2: Towards Evaluating The Differential Privacy of a Function
Evaluate if result of query is leaking "private" information and how much of privacy is leaked. Measure the _maximum_ amount the query changes when someone is removed (maximum over all possible people who could be removed). Iterate over each person in the database and measure the difference in the output of the query relative to when query the entire database. Measure the ***sensitivity of sum() function***.

##GLOSSARY:

**L1 Sensitivity** (or in short sensitivity) is the maximum amount that the query changes when removing an individual from the database. 

In [0]:
# importing torch
import torch

In [0]:
# the number of entries in database
num_entries = 5000

# will cretae a random tensor with 0's and 1's 
db = torch.rand(num_entries) > 0.5
db

tensor([1, 0, 1,  ..., 1, 1, 1], dtype=torch.uint8)

In [0]:
remove_index = 2

In [0]:
def get_paraller_db(db, remove_index):
  

  return torch.cat((db[0:remove_index], 
                    db[remove_index+1:]))

In [0]:
get_paraller_db(db,3).shape

torch.Size([4999])

In [0]:
def get_parallel_dbs(db):
  
  parallel_dbs = list()

  for i in range(len(db)):
     pdb = get_paraller_db(db, i)
     parallel_dbs.append(pdb)
    
  return parallel_dbs

In [0]:
pdbs = get_parallel_dbs(db)

In [0]:
def create_db_and_parallels(um_entries):
  
  db = torch.rand(num_entries) > 0.5
  pdbs = get_parallel_dbs(db)
  
  return db, pdbs

In [0]:
db, pdbs = create_db_and_parallels(20)

In [0]:
db 

tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8)

In [0]:
pdbs

[tensor([1, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1

In [0]:
def query (db):
  return db.sum()

In [0]:
full_db_result = query(db)

In [0]:
sensitivity = 0 #sensitivity = max_distance
for pdb in pdbs:
  pdb_result = query(pdb)
  
  db_distance = torch.abs(pdb_result - full_db_result)
  
  if(db_distance > sensitivity):
    sensitivity = db_distance

In [0]:
sensitivity

tensor(1)