<a href="https://colab.research.google.com/github/agatagruza/private-ai/blob/master/SPAIC_Project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project 1: Generate Parallel Database
Create a list of every parallel database to the one currently contained in the "db" variable. Create a function which both:
- creates the initial database (db)
- creates all parallel databases

In [0]:
# importing torch
import torch

In [2]:
# the number of entries in database
num_entries = 5000

# will cretae a random tensor with 0's and 1's 
db = torch.rand(num_entries) > 0.5
db

tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8)

In [5]:
db.shape

torch.Size([5000])

In [6]:
db[0:5]

tensor([1, 1, 0, 1, 0], dtype=torch.uint8)

In [0]:
remove_index = 2

In [0]:
def get_paraller_db(db, remove_index):
  

  return torch.cat((db[0:remove_index], 
                    db[remove_index+1:]))

In [15]:
get_paraller_db(db,3).shape

torch.Size([4999])

In [19]:
# for num_entries > 5000 it won't throw error. Inteaed it will print whole db
get_paraller_db(db, 52352).shape

torch.Size([5000])

In [0]:
def get_parallel_dbs(db):
  
  parallel_dbs = list()

  for i in range(len(db)):
     pdb = get_paraller_db(db, i)
     parallel_dbs.append(pdb)
    
  return parallel_dbs

In [0]:
pdbs = get_parallel_dbs(db)

In [25]:
pdbs

[tensor([1, 0, 1,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 1,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0

In [26]:
len(parallel_dbs)

5000

In [0]:
def create_db_and_parallels(um_entries):
  
  db = torch.rand(num_entries) > 0.5
  pdbs = get_parallel_dbs(db)
  
  return db, pdbs

In [0]:
db, pdbs = create_db_and_parallels(20)

In [29]:
db

tensor([1, 1, 0,  ..., 0, 1, 0], dtype=torch.uint8)

In [31]:
pdbs

[tensor([1, 0, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 1